name: dashboard
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  utilities:
    git:
      url: https://github.com/SinaMN75/Utilities-flutter.git
      ref: main

  syncfusion_localizations: ^20.3.47
  syncfusion_flutter_datagrid_export: ^20.3.47-beta
  syncfusion_flutter_calendar: ^20.3.47
  syncfusion_flutter_datepicker: ^20.3.47
  syncfusion_flutter_charts: ^20.3.47
  syncfusion_flutter_gauges: ^20.3.47
  syncfusion_flutter_sliders: ^20.3.47
  syncfusion_flutter_pdf: ^20.3.47
  syncfusion_flutter_barcodes: ^20.3.47
  syncfusion_officechart: ^20.3.47-beta
  syncfusion_flutter_maps: ^20.3.47
  syncfusion_flutter_signaturepad: ^20.3.47
  syncfusion_flutter_pdfviewer: ^20.3.47-beta
  syncfusion_flutter_treemap: ^20.3.47-beta

dev_dependencies:
  flutter_launcher_icons: ^0.9.1
  flutter_lints: ^1.0.0

#  flutter pub global activate rename
#  flutter pub global run rename --bundleId com.example.app
#  flutter pub global run rename --appname example
#  flutter pub run flutter_launcher_icons:main
flutter_icons:
  image_path_android: "lib/assets/images/logo.png"
  image_path_ios: "lib/assets/images/logo.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - lib/assets/icons/
    - lib/assets/images/
    - lib/assets/fonts/

  fonts:
    - family: IRANSansMobile
      fonts:
        - asset: lib/assets/fonts/IRANSansMobile.ttf

flutter_intl:
  enabled: true